### PR TITLE
Add a question about exp-run

### PR DESCRIPTION
**Pull request by iblislin**

### CODE REVIEW

**Comment by iblislin** [comment]
Thanks! 
I googled this term, but no answer ...

**Comment by koobs** [comment]
Answer has been added, thanks for submitting the question!

Btw, where did you find a link to this repo? :)

**Comment by iblislin** [comment]
@koobs This repo is on [your profile page](https://github.com/koobs). 👍

Or ... what is the expected way to find this repo?

**Comment by koobs** [comment]
@iblis17 Ah! I had tweeted about it a long time ago :)

**Pull request merged**
